web:
  build: .
  links:
    - mysql:mysql
    - elasticsearch:elasticsearch
  ports:
    - "80:80"
    - "443:443"
    - "9000:9000"
  volumes:
    - "./www:/var/www"
    - "./conf/nginx/conf.d:/etc/nginx/conf.d"

mysql:
  image: mysql
  ports:
      - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_DATABASE: magento
    MYSQL_USER: magento
    MYSQL_PASSWORD: password

elasticsearch:
  image: elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"