web:
  build: .
  container_name: magento2_web
  links:
    - mysql:mysql
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - "./www:/var/www"
    - "./conf/nginx/conf.d:/etc/nginx/conf.d"

mysql:
  image: mysql
  container_name: magento2_mysql
  ports:
      - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_DATABASE: magento
    MYSQL_USER: magento
    MYSQL_PASSWORD: password